#!/bin/sh

DIR=$(cd $(dirname "$0")/../..; pwd)
cd "$DIR"

TAG_NAME="${GITHUB_REF#refs/tags/}"

[ -n "$TAG_NAME" ] || {
    echo 'No tag' >&2
    exit 1
}
case "$TAG_NAME" in
v0*|v1*|v2*|v3*|v4*|v5*|v6*|v7*|v8*|v9*) ;;
*)
    echo 'Not a release tag' >&2
    exit 1 ;;
esac

type gobump >/dev/null || go get github.com/x-motemen/gobump/cmd/gobump
[ "$TAG_NAME" = "v$(gobump show -r)" ] || {
    echo "Invalid tag: $TAG_NAME != v$(gobump show -r)" >&2
    exit 1
}

script/can-release || exit 1
