#!/bin/sh

set -x

BRANCH="${GIT_BRANCH:-$(git branch --show-current)}"
[ "$BRANCH" = 'master' ] || exit

git checkout "$BRANCH"

go run script/genauthors/genauthors.go --format=markdown > AUTHORS.md
[ "$?" = 0 ] || git checkout AUTHORS.md

git config --global user.email 'fireworq.github@gmail.com'
git config --global user.name 'fireworq-bot'

git add AUTHORS.md
git commit -m "Update the list of authors."
git push --quiet origin master
