name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: script/ci/test/docker-run
    - name: Setup Go for gcov2lcov
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.8
      with:
        infile: profile.cov
        outfile: coverage.lcov
    - name: Report coverage to Coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
